# Use the official ASP.NET Core runtime as the base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Enable HTTPS in Docker
# Enable HTTPS and specify certificate location inside Docker
ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_URLS=http://+:8080

# Expose ports as per launchSettings.json
EXPOSE 8080

# Use the .NET 8 SDK for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy project file and restore dependencies
COPY ["ShoyerNetBlazor.csproj", "./"]
RUN dotnet restore "ShoyerNetBlazor.csproj"

# Copy everything and build the application
COPY . .
RUN dotnet publish "ShoyerNetBlazor.csproj" -c Release -o /app/publish

# Final stage: Create the runtime image
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

# Set environment variables for port bindings
#ENV ASPNETCORE_URLS="http://+:8080;https://+:7015"
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false


# Start the application
ENTRYPOINT ["dotnet", "ShoyerNetBlazor.dll"]
